name: "CI"
on:
 - push
 - pull_request

jobs:
  test_and_build:
    runs-on: "ubuntu-20.04"
    name: >-
      Test on
      Elixir ${{ matrix.elixir }} and Erlang/OTP ${{ matrix.otp }}
      ${{ matrix.update-deps && 'with the latest dependencies' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test on all supported releases.
          - { elixir: '1.11', otp: '24' }
          - { elixir: '1.12', otp: '24' }
          - { elixir: '1.13', otp: '24' }
          - { elixir: '1.13', otp: '25' }
          - { elixir: '1.14', otp: '24' }
          - { elixir: '1.14', otp: '25' }
          - { elixir: '1.14', otp: '25', update-deps: true }
    steps:
    - uses: actions/checkout@v3

    - name: Setup dependency cache
      uses: actions/cache@v3
      with:
        path: |
          deps
        key: mix-${{ hashFiles('mix.lock') }}

    - name: Setup binary cache
      uses: actions/cache@v3
      with:
        path: |
          _build
          priv/plts
        key: ${{ matrix.elixir }}-${{ matrix.otp }}

    - name: Setup beam
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Unlock dependencies to get latest
      if: ${{ matrix.update-deps }}
      run: mix deps.unlock --all

    - name: Fetch dependencies
      run: mix deps.get

    - name: Run linters
      run: mix lint

    # TODO: Tests should pass on the main branch.
    # - name: Run tests
    #  run: mix test
