name: "CI"
on:
 - push
 - pull_request

jobs:
  test_and_build:
    runs-on: "ubuntu-20.04"
    name: "Elixir ${{ matrix.elixir }} test"
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test on all supported releases. Compatibility matrix from
          # https://hexdocs.pm/elixir/1.12/compatibility-and-deprecations.html
          #
          # These pin to the lowest supported OTP for each elixir release.
          - { elixir: '1.10', otp: '21' }
          - { elixir: '1.11', otp: '21' }
          - { elixir: '1.12', otp: '22' }
          - { elixir: '1.13', otp: '22' }
          - { elixir: '1.14', otp: '23', update-deps: true }
    steps:
    - uses: actions/checkout@v3

    - name: Setup dependency cache
      uses: actions/cache@v3
      with:
        path: |
          deps
        key: mix-${{ hashFiles('mix.lock') }}

    - name: Setup binary cache
      uses: actions/cache@v3
      with:
        path: |
          _build
          priv/plts
        key: ${{ matrix.elixir }}-${{ matrix.otp }}

    - name: Setup beam
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Unlock dependencies to get latest
      if: ${{ matrix.update-deps }}
      run: mix deps.unlock --all

    - name: Fetch dependencies
      run: mix deps.get

    - name: Run linters
      run: mix lint

    # TODO: Tests should pass on the main branch.
    # - name: Run tests
    #  run: mix test
